---
- name: Configure LLM Pi.
  hosts: llm_pi
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure yq is installed.
      ansible.builtin.apt:
        name: yq
        state: present

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Set up Ollama + n8n.
      ansible.builtin.import_tasks: tasks/ollama-n8n.yml

    - name: Set up automatic image updates.
      ansible.builtin.import_tasks: tasks/update.yml
